import { useQuery } from '@tanstack/react-query';
import { briefingService } from '../services/briefing';
import { FileClock, Calendar, AlertTriangle, Trophy, HelpCircle, ArrowRight, X } from 'lucide-react';
import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

export default function HistoryPage() {
  const [selectedBriefingId, setSelectedBriefingId] = useState<number | null>(null);

  const { data: history, isLoading } = useQuery({
    queryKey: ['briefingHistory'],
    queryFn: briefingService.getBriefingHistory,
  });

  const selectedBriefing = history?.find(b => b.id === selectedBriefingId);

  if (isLoading || !history) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center min-h-[400px]">
        <div className="w-10 h-10 border-4 border-brandPurple/30 border-t-brandPurple rounded-full animate-spin mb-4" />
        <span className="text-sm text-gray-400">Loading history logs...</span>
      </div>
    );
  }

  return (
    <div className="space-y-6 relative">
      <div>
        <p className="text-sm text-gray-400">
          Review all previous briefings generated by FlowBrain to track your startups development over time.
        </p>
      </div>

      {/* History List */}
      <div className="space-y-4">
        {history.map((item) => (
          <div
            key={item.id}
            onClick={() => setSelectedBriefingId(item.id)}
            className="p-5 rounded-2xl border border-[#1C2A3A] bg-[#0D1117] hover:border-brandPurple/40 cursor-pointer flex flex-col md:flex-row md:items-center justify-between gap-4 transition-all duration-200"
          >
            <div className="flex items-start gap-4">
              <div className="p-3 bg-white/[0.02] border border-[#1C2A3A] rounded-xl text-brandPurple mt-0.5">
                <FileClock size={20} />
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <Calendar size={12} className="text-gray-500" />
                  <span className="text-xs text-gray-500 font-semibold">
                    {new Date(item.generated_at).toLocaleDateString(undefined, {
                      weekday: 'long',
                      year: 'numeric',
                      month: 'long',
                      day: 'numeric'
                    })}
                  </span>
                </div>
                <h4 className="font-heading text-base font-bold text-white mt-1.5 leading-snug">
                  {item.focus}
                </h4>
              </div>
            </div>

            {/* Metrics pills */}
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-4 border-r border-[#1C2A3A] pr-6 text-xs font-semibold">
                <div className="flex items-center gap-1.5 text-brandRed bg-brandRed/10 px-2 py-1 rounded-lg">
                  <AlertTriangle size={12} />
                  <span>{item.breaks_count}</span>
                </div>
                <div className="flex items-center gap-1.5 text-brandAmber bg-brandAmber/10 px-2 py-1 rounded-lg">
                  <HelpCircle size={12} />
                  <span>{item.decisions_count}</span>
                </div>
                <div className="flex items-center gap-1.5 text-brandGreen bg-brandGreen/10 px-2 py-1 rounded-lg">
                  <Trophy size={12} />
                  <span>{item.wins_count}</span>
                </div>
              </div>
              <div className="text-brandPurple hover:text-white p-2 transition-colors hidden md:block">
                <ArrowRight size={16} />
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Briefing Detail Modal */}
      <AnimatePresence>
        {selectedBriefingId && selectedBriefing && (
          <div className="fixed inset-0 bg-[#07090F]/80 backdrop-blur-md flex justify-end z-50">
            <motion.div
              initial={{ x: '100%' }}
              animate={{ x: 0 }}
              exit={{ x: '100%' }}
              transition={{ type: 'spring', damping: 25, stiffness: 200 }}
              className="w-full max-w-xl bg-[#0D1117] border-l border-[#1C2A3A] h-screen flex flex-col shadow-2xl overflow-y-auto"
            >
              {/* Modal Header */}
              <div className="p-6 border-b border-[#1C2A3A] flex items-center justify-between">
                <div>
                  <span className="text-[10px] text-brandPurple font-bold uppercase tracking-wider">
                    Historical Log Archive
                  </span>
                  <h3 className="font-heading text-lg font-bold text-white mt-1">
                    Briefing Details #{selectedBriefing.id}
                  </h3>
                </div>
                <button
                  onClick={() => setSelectedBriefingId(null)}
                  className="p-2 rounded-xl border border-[#1C2A3A] hover:bg-white/5 text-gray-400 hover:text-white transition-all"
                >
                  <X size={16} />
                </button>
              </div>

              {/* Modal Content */}
              <div className="p-6 space-y-6">
                <div className="flex items-center gap-2 text-xs text-gray-500 font-medium">
                  <Calendar size={14} />
                  <span>Generated on: {new Date(selectedBriefing.generated_at).toLocaleString()}</span>
                </div>

                <div className="p-4 rounded-xl bg-white/[0.01] border border-[#1C2A3A]">
                  <span className="text-xs font-semibold text-brandPurple block mb-1">#1 Strategic Focus</span>
                  <p className="text-sm font-semibold text-white leading-relaxed">{selectedBriefing.focus}</p>
                </div>

                <div className="space-y-4">
                  <h4 className="font-heading text-xs font-bold uppercase text-gray-500 tracking-wider">
                    Signals Analysis Summary
                  </h4>

                  <div className="space-y-3">
                    <div className="flex items-start justify-between p-3 rounded-lg bg-brandRed/5 border border-brandRed/10 text-xs">
                      <div className="flex items-center gap-2 text-brandRed font-semibold">
                        <AlertTriangle size={14} />
                        <span>Critical Blockers</span>
                      </div>
                      <span className="font-bold text-white">{selectedBriefing.breaks_count} flagged</span>
                    </div>

                    <div className="flex items-start justify-between p-3 rounded-lg bg-brandAmber/5 border border-brandAmber/10 text-xs">
                      <div className="flex items-center gap-2 text-brandAmber font-semibold">
                        <HelpCircle size={14} />
                        <span>Actionable Decisions</span>
                      </div>
                      <span className="font-bold text-white">{selectedBriefing.decisions_count} flagged</span>
                    </div>

                    <div className="flex items-start justify-between p-3 rounded-lg bg-brandGreen/5 border border-brandGreen/10 text-xs">
                      <div className="flex items-center gap-2 text-brandGreen font-semibold">
                        <Trophy size={14} />
                        <span>Milestone Wins</span>
                      </div>
                      <span className="font-bold text-white">{selectedBriefing.wins_count} flagged</span>
                    </div>
                  </div>
                </div>

                <div className="p-4 rounded-xl border border-dashed border-[#1C2A3A] text-center text-xs text-gray-500">
                  Detailed integrations snapshots are archived in Supabase storage logs.
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
