"""add_is_excluded_to_emails

Revision ID: 3c868e58b45a
Revises: 85fa705e48a0
Create Date: 2026-06-22 12:10:05.125005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c868e58b45a'
down_revision: Union[str, Sequence[str], None] = '85fa705e48a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('is_excluded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'is_excluded')
    # ### end Alembic commands ###
