"""add_body_full_to_emails

Revision ID: 8838a3298605
Revises: b93beb12918c
Create Date: 2026-06-20 17:23:06.924094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8838a3298605'
down_revision: Union[str, Sequence[str], None] = 'b93beb12918c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('body_full', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'body_full')
    # ### end Alembic commands ###
